version: "20.10.23"
services:
  bug-tracker:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/APP:ro
      - /APP/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - MONGO_USER=bug-tracker
      - MONGO_PASSWORD=daniel1
      - MONGO_
    command: npm run dev

  mongo: 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bug-tracker
      - MONGO_INITDB_ROOT_PASSWORD=daniel1
     