version: "20.10.23"
services:
  bug-tracker:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/APP
      - /APP/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=password123
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27018:27017"
