version: "20.10.23"
services:
  bug-tracker:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-db:
