version: "20.10.23"
services:
  bug-tracker:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  
  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bug-tracker
      - MONGO_INITDB_ROOT_PASSWORD=daniel1
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: