name: Build and Start App

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19.8.1"

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

  start:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: npm ci

      - name: Start App
        run: npm run start
